"""SQLAlchemy 2.x declarative foundation for the Enterprise ERP (SIWRMS).

This module is the **sole** owner of the project's ``MetaData`` and the
declarative ``Base`` class. Every future ORM model subclasses ``Base`` and
consequently resolves its constraints / indexes / foreign keys against the
single shared ``metadata`` instance built here, which is in turn bound to the
spec-mandated ``NAMING_CONVENTION`` (from ``database/naming.py``) and the
application schema ``erp`` (``database.constants.APP_SCHEMA``).

Scope of this file — deliberately minimal:

* ``metadata``  — the shared ``MetaData`` (naming convention + target schema).
* ``Base``      — a SQLAlchemy 2.x ``DeclarativeBase`` bound to that metadata.
* ``GuidPk``    — a typed ``Mapped[uuid.UUID]`` annotation produced by
  ``id_column()``, the reusable, mixin-free UUID primary-key helper that the
  spec's "every table's surrogate PK is ``id UUID NOT NULL DEFAULT
  gen_random_uuid()``" contract calls for.

OUT OF SCOPE here (and therefore NOT present):

* No mixin classes (no audit / timestamp / soft-delete / optimistic-lock etc.).
* No ORM models / ``__tablename__`` declarations.
* No custom SQLAlchemy ``TypeDecorator`` types (those belong in a future
  ``types.py`` — explicitly NOT created by this task).
* No session/engine/``sessionmaker`` plumbing (future ``session.py``).
* No Alembic artifacts.

Authority:
    - 07_DATABASE_SPEC.md  (every surrogate PK: ``id UUID NOT NULL DEFAULT
      gen_random_uuid()``; naming convention prefixes ``pk_<table>`` etc.)
    - database/naming.py  (``NAMING_CONVENTION`` is the single source of truth
      for ``MetaData.naming_convention``).
    - database/constants.py (``APP_SCHEMA`` = ``erp``, PostgreSQL 17 target).
"""

from __future__ import annotations

import uuid
from typing import Any

from sqlalchemy import MetaData
from sqlalchemy import Uuid as _SAUuid
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.sql import func

from database.constants import APP_SCHEMA
from database.naming import NAMING_CONVENTION

# ---------------------------------------------------------------------------
# Shared MetaData
# ---------------------------------------------------------------------------
#: The single, project-wide ``MetaData`` instance.
#:
#: Bound to:
#:   * ``naming_convention`` — ``NAMING_CONVENTION`` from ``database/naming.py``,
#:     so every PK / FK / unique / check / index name generated by SQLAlchemy
#:     for *unnamed* constraints follows the spec's ``pk_<table>`` /
#:     ``fk_<table>_<col>_<ref>_<refcol>`` / ``uq_<table>_<col>`` /
#:     ``ck_<table>_<name>`` / ``idx_<table>_<col>`` convention deterministically.
#:     (Hand-authored constraint names passed with an explicit ``name=`` always
#:     win — the convention only governs the unnamed-fallback path.)
#:   * ``schema`` — ``APP_SCHEMA`` (``erp``), so every table built on ``Base``
#:     is created in the application schema by default without each model
#:     having to repeat ``__table_args__ = {"schema": ...}``.
#:
#: This object is the only ``MetaData`` the declarative ``Base`` (below) and,
#: by extension, every domain model registers its tables against.
metadata: MetaData = MetaData(
    naming_convention=NAMING_CONVENTION,
    schema=APP_SCHEMA,
)


# ---------------------------------------------------------------------------
# Declarative base (SQLAlchemy 2.x style)
# ---------------------------------------------------------------------------
class Base(DeclarativeBase):
    """Project-wide declarative base for all ORM models.

    SQLAlchemy 2.x style: subclasses ``DeclarativeBase`` directly (rather than
    the legacy ``declarative_base()`` factory) so that ``Mapped``/``mapped_column``
    type-annotated columns resolve against this class's registry. The class's
    registry is bound to the shared ``metadata`` above by passing it as the
    class-level ``metadata`` attribute — the documented mechanism for pinning
    a custom ``MetaData`` to a ``DeclarativeBase`` subclass.

    Models subclass this base; the ``metadata`` and ``registry`` are shared so
    that ``Base.metadata`` (and ``metadata`` directly) enumerate all known
    tables, and constraint / index naming stays spec-compliant by construction.
    """

    metadata: MetaData = metadata


# ---------------------------------------------------------------------------
# UUID primary-key helper (inline; NO mixins.py)
# ---------------------------------------------------------------------------
#: ``Mapped`` annotation type alias for a UUID primary key.
#:
#: Returned by :func:`id_column` so models can declare their surrogate PK as
#: ``id: GuidPk = id_column()``. Aliased purely to keep model column
#: declarations concise and self-documenting — it is *not* a class/mixin, and
#: carries no attributes or behavior of its own (it is just ``Mapped[uuid.UUID]``).
GuidPk = Mapped[uuid.UUID]


def id_column() -> Mapped[uuid.UUID]:
    """Return the reusable ``Mapped[uuid.UUID]`` annotation for a UUID PK.

    Encodes the database spec's universal surrogate-PK contract:

        | id | UUID | NOT NULL | gen_random_uuid() | Surrogate PK |

    Concretely the produced ``Mapped`` maps via ``mapped_column`` to:

    * ``type_``        — ``Uuid(as_uuid=True)``  (PostgreSQL native ``uuid``;
      read back as Python ``uuid.UUID``, never raw ``str``).
    * ``primary_key`` — ``True``               (the table's sole PK).
    * ``nullable``     — ``False``              (``NOT NULL``).
    * ``name``         — ``"id"``               (the spec's universal PK name).
    * ``server_default`` — ``gen_random_uuid()`` (PostgreSQL 17's built-in
      function; emitted as the column's ``DEFAULT`` so INSERTs that omit ``id``
      get a server-generated UUID, the spec's exact ``DEFAULT`` clause).

    Usage in a future model (NOT in this file — models are out of scope here)::

        class Shipment(Base):
            __tablename__ = "shipment"
            id: GuidPk = id_column()

    This helper is intentionally mixin-free: it returns a typed
    ``Mapped[uuid.UUID]`` annotation rather than introducing a base class that
    injects the column, so each model opts in explicitly and the mapping is
    fully visible at the model definition site. No opt-out column, no
    inheritance surprise, no ``__init_subclass__`` side effects.

    Args:
        None.

    Returns:
        ``Mapped[uuid.UUID]`` — the type-annotated primary-key column,
        ready to be assigned to a ``Mapped`` attribute on a ``DeclarativeBase``
        subclass.
    """

    return mapped_column(
        _SAUuid(as_uuid=True),
        primary_key=True,
        nullable=False,
        name="id",
        server_default=func.gen_random_uuid(),
    )


__all__ = [
    "Base",
    "GuidPk",
    "id_column",
    "metadata",
]
