"""``R5 — currency`` ORM model (ISO 4217 reference table).

Authority: docs/06_ERD.md, PART B → ``R5 — currency``::

    R5 — currency
    Purpose: Currency reference (ISO 4217).
    PK: id | code unique (e.g. USD)
    Important fields: symbol, decimals, is_base
    Classification: R

This entity has **no entry in docs/07_DATABASE_SPEC.md** — PART B reference
tables were not ported into the physical spec; the ERD is the source of truth
for ``currency``'s own columns, and the spec only references ``currency`` as a
foreign-key target elsewhere (``currency_id UUID NOT NULL FK`` on
``shipment``/``invoice``/``payment``/``order``/``inventory_transaction`` etc.).

Audit-column family — ``UniversalAuditColumns`` (UAC):
    ``created_at`` / ``updated_at`` / ``created_by`` / ``updated_by`` / ``version``.
    The ERD's §0.2 Governing Design Decisions states audit fields are stored by
    *every* table, so R-class editable reference tables adopt UAC. ``currency``
    gets UAC **without** ``deleted_at`` / soft-delete: the ERD does not list a
    soft-delete column for R5, and you do not "soft-delete" an ISO 4217 currency
    (you flip ``is_base`` or stop referencing it) — so the model deliberately
    omits ``deleted_at``. (``UniversalAuditColumns`` as defined in
    ``database.mixins`` already carries no ``deleted_at``, so no deviation from
    the mixin is required — it's used as-is.)

Optimistic locking:
    ``__mapper_args__ = {"version_id_col": "version"}`` opts the model into the
    UAC ``version`` column as the SQLAlchemy row-version concurrency token (per
    ``database.mixins``'s documented opt-in mechanism — the mixin supplies the
    column, the model wires the mapper).

Naming convention:
    Constraint/index names are generated by ``database.naming.NAMING_CONVENTION``
    (bound to the shared ``MetaData`` in ``database.base``). The column-level
    ``unique=True`` on ``code`` therefore auto-named to ``uq_currency_code``
    (convention: ``uq_%(table_name)s_%(column_0_name)s``). The partial
    single-base-currency index is hand-authored and given an explicit name via
    ``database.naming.idx_index_name("currency", "one_base")`` →
    ``idx_currency_one_base`` (the ``ix`` convention governs only implicit
    indexes, so explicit index names pass through untouched). The ``decimals``
    range CHECK uses ``database.naming.ck_index_name("currency",
    "decimals_range")``, which returns the bare descriptor ``decimals_range``;
    the convention's ``ck`` template ``ck_%(table_name)s_%(constraint_name)s``
    supplies the ``ck_currency_`` prefix at compile time, rendering
    ``ck_currency_decimals_range`` verbatim.

Column-type notes:
    * ``code`` uses plain ``String(3)`` rather than a ``database.types`` helper
      or a ``StringLength`` member: ISO 4217 alpha-3 currency codes are a fixed
      one-off width (3 chars), not a reusable project-wide length contract — no
      ``StringLength.CURRENCY_CODE`` exists and we are told not to invent
      lengths. A bare ``String(3)`` is the precise, minimal choice.
    * ``symbol`` uses plain ``String(16)``: no existing ``StringLength`` member
      fits a short currency symbol (e.g. "$", "€", "﷼"). We do NOT invent a new
      ``StringLength`` member without being asked; 16 chars covers every known
      ISO 4217 symbol and any reasonable unicode glyph.
"""

from __future__ import annotations

from sqlalchemy import Boolean, CheckConstraint, Index, SmallInteger, String
from sqlalchemy import text as sa_text
from sqlalchemy.orm import Mapped, mapped_column

from database.base import Base, GuidPk, id_column
from database.mixins import UniversalAuditColumns
from database.naming import ck_index_name, idx_index_name


class Currency(Base, UniversalAuditColumns):
    """``R5 — currency`` — ISO 4217 currency reference (Classification: R)."""

    __tablename__ = "currency"

    # Optimistic locking — activate the UAC ``version`` column as the
    # SQLAlchemy row-version concurrency token (mixins.py opt-in mechanism).
    __mapper_args__ = {"version_id_col": "version"}

    # ------------------------------------------------------------------ id
    id: GuidPk = id_column()

    # ------------------------------------------------------------------ code
    # Plain ``String(3)`` rather than a ``database.types`` helper or a
    # ``StringLength`` member: ISO 4217 alpha-3 currency codes are a fixed
    # one-off width (3 chars), not a reusable project-wide length contract.
    code: Mapped[str] = mapped_column(
        String(3),
        nullable=False,
        unique=True,
    )

    # -------------------------------------------------------------- symbol
    # Plain ``String(16)``: no existing ``StringLength`` member fits a short
    # currency symbol (e.g. "$", "€", "﷼"). We do NOT invent a new
    # ``StringLength`` member without being asked; 16 chars covers every
    # known ISO 4217 symbol and any reasonable unicode glyph.
    symbol: Mapped[str] = mapped_column(
        String(16),
        nullable=False,
    )

    # ------------------------------------------------------------ decimals
    # Integer count-of-decimal-places for this currency (e.g. USD=2, IRR=0).
    # ``SmallInteger`` is the right width (range ample for 0..4). Default 2 is
    # the ISO 4217 default fraction digits for most currencies. The CHECK
    # bounds it to [0, 4] per ISO 4217's observed range.
    decimals: Mapped[int] = mapped_column(
        SmallInteger(),
        nullable=False,
        default=2,
        server_default=sa_text("2"),
    )

    # -------------------------------------------------------------- is_base
    # Whether this row is the org's single base / ledger currency. Default
    # ``False``. The "exactly one base" invariant is enforced by the partial
    # unique index declared in ``__table_args__`` (see comment there) — a
    # documented extension the ERD does not explicitly state for R5.
    is_base: Mapped[bool] = mapped_column(
        Boolean(),
        nullable=False,
        default=False,
        server_default=sa_text("false"),
    )

    # ------------------------------------------------------------------ constraints
    __table_args__ = (
        # CHECK: decimals range. Named via the convention helper: ``ck_index_name``
        # returns the bare descriptor (see its docstring — ``NAMING_CONVENTION["ck"]``
        # supplies the ``ck_<table>_`` prefix at compile time), so the produced DDL
        # reads ``ck_currency_decimals_range`` verbatim.
        CheckConstraint(
            "decimals >= 0 AND decimals <= 4",
            name=ck_index_name("currency", "decimals_range"),
        ),
        # Deviation note (NOT in the ERD's R5 entry): enforce the single
        # base-currency invariant with a partial unique index that admits at
        # most one row with ``is_base = true``. Mirrors the project's existing
        # conditional-uniqueness idiom (e.g. exactly one ``warehouse.type =
        # 'FACTORY'`` active). Hand-authored name via ``idx_index_name`` →
        # ``idx_currency_one_base``.
        Index(
            idx_index_name("currency", "one_base"),
            "is_base",
            unique=True,
            postgresql_where=sa_text("is_base = true"),
        ),
    )


__all__ = ["Currency"]
